version: "3.9"

networks:
  default:
    name: backend-lesson

services:
  web:
    image: node:18.15.0
    user: "node"
    working_dir: /home/node/app
    environment:
      - PORT=3000
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
    extra_hosts: # For Linux
      - "host.docker.internal:host-gateway"
    tty: true
    expose:
      - "3000"
    command: "npm run dev"
